apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      name: todo-api-pod
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api
          image: pavanelthepu/todo-api:1.0.2
          ports:
            - containerPort: 8082
          env:
            - name: "spring.data.mongodb.uri"
              value: "mongodb+srv://root:321654@cluster0.p9jq2.mongodb.net/todo?retryWrites=true&w=majority"
      affinity:
        podAffinity: # you can also use "podAntiAffinity" to avoid scheduling pods together
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - todo-ui
            topologyKey: "kubernetes.io/hostname"
# This is how we collocate the Pods on the same node, in this example we are collocating the todo-api pods with the todo-ui pods, so that they can communicate with each other with low latency. The topologyKey is set to "kubernetes.io/hostname" which means that the pods will be scheduled on the same node. You can also use other topology keys like "topology.kubernetes.io/zone" or "topology.kubernetes.io/region" to collocate pods in the same zone or region respectively.