apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]  # Define what resources are being accessed
  verbs: ["get", "watch", "list"]   # Define the actions that can be performed on the resources